<?php

/*
 * This file is part of the Kuiper package.
 *
 * (c) Ye Wenbin <wenbinye@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

declare(strict_types=1);

/**
 * NOTE: This class is auto generated by Tars Generator (https://github.com/wenbinye/tars-generator).
 *
 * Do not edit the class manually.
 * Tars Generator version: 1.0
 */

namespace kuiper\tars\fixtures;

use kuiper\tars\annotation\TarsClient;
use kuiper\tars\annotation\TarsParameter;
use kuiper\tars\annotation\TarsReturnType;

/**
 * @TarsClient("PHPDemo.PHPTcpServer.UserObj")
 */
interface UserServant
{
    /**
     * @TarsParameter(name="id", type="int")
     * @TarsReturnType("User")
     *
     * @param int $id
     *
     * @return User
     */
    public function findUser(int $id): User;

    /**
     * @TarsParameter(name="user", type="User")
     * @TarsReturnType("void")
     *
     * @param User $user
     *
     * @return void
     */
    public function saveUser(User $user): void;

    /**
     * @TarsParameter(name="total", type="int", out=true)
     * @TarsReturnType("vector<User>")
     *
     * @param int $total
     *
     * @return User[]
     */
    public function findAllUser(?int &$total): array;
}
