<?php

/*
 * This file is part of the Kuiper package.
 *
 * (c) Ye Wenbin <wenbinye@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */


declare(strict_types=1);

/**
 * NOTE: This class is auto generated by Tars Generator (https://github.com/wenbinye/tars-generator).
 *
 * Do not edit the class manually.
 * Tars Generator version: 0.6
 */

namespace kuiper\tars\integration;

use kuiper\tars\attribute\TarsClient;
use kuiper\tars\attribute\TarsParameter;
use kuiper\tars\attribute\TarsReturnType;

#[TarsClient("tars.tarsconfig.ConfigObj")]
interface ConfigServant
{
    /**
     * 读取配置文件列表
     * @tars-param app, app name
     * @tars-param server, server name
     * @tars-param vf, config file name
     * /
     */
    #[TarsReturnType("int")]
    public function ListConfig(
        #[TarsParameter(type: "string")] string $app,
        #[TarsParameter(type: "string")] string $server,
        #[TarsParameter(type: "vector<string>")] ?array &$vf
    ): int;

    /**
     * 读取配置文件
     * @tars-param app, app name
     * @tars-param server, server name
     * @tars-param filename, config file name
     * @tars-param config, 配置文件内容
     * /
     */
    #[TarsReturnType("int")]
    public function loadConfig(
        #[TarsParameter(type: "string")] string $app,
        #[TarsParameter(type: "string")] string $server,
        #[TarsParameter(type: "string")] string $filename,
        #[TarsParameter(type: "string")] ?string &$config
    ): int;

    /**
     * 根据host读取文件
     * @tars-param appSerever, app.server
     * @tars-param filename, config file name
     * @tars-param host, ip
     * @tars-param config, 配置文件内容
     * /
     */
    #[TarsReturnType("int")]
    public function loadConfigByHost(
        #[TarsParameter(type: "string")] string $appServerName,
        #[TarsParameter(type: "string")] string $filename,
        #[TarsParameter(type: "string")] string $host,
        #[TarsParameter(type: "string")] ?string &$config
    ): int;

    /**
     * 检查配置文件是否服务TC_Config格式
     * @tars-param appSerever, app.server
     * @tars-param filename, config file name
     * @tars-param host, ip
     * @tars-param result, 提示
     * @tars-return int 0: 合法, -1:非法
     * /
     */
    #[TarsReturnType("int")]
    public function checkConfig(
        #[TarsParameter(type: "string")] string $appServerName,
        #[TarsParameter(type: "string")] string $filename,
        #[TarsParameter(type: "string")] string $host,
        #[TarsParameter(type: "string")] ?string &$result
    ): int;

    /**
     * 读取服务所在节点的配置文件列表
     * 
     * @tars-param configInfo, ConfigInfo 配置文件信息，如果没有set分组信息，请设置setdivision为空""
     * @tars-param vf, config file name
     * @tars-return int 0: 成功, -1:失败
     * /
     */
    #[TarsReturnType("int")]
    public function ListConfigByInfo(
        #[TarsParameter(type: "ConfigInfo")] ConfigInfo $configInfo,
        #[TarsParameter(type: "vector<string>")] ?array &$vf
    ): int;

    /**
     * 读取配置文件
     * @tars-param configInfo, ConfigInfo 配置文件信息
     * @tars-param config, 配置文件内容
     * @tars-return int 0: 成功, -1:失败
     * /
     */
    #[TarsReturnType("int")]
    public function loadConfigByInfo(
        #[TarsParameter(type: "ConfigInfo")] ConfigInfo $configInfo,
        #[TarsParameter(type: "string")] ?string &$config
    ): int;

    /**
     * 检查配置文件是否符合TC_Config格式
     * @tars-param configInfo, ConfigInfo 配置文件信息
     * @tars-param result, 提示
     * @tars-return int 0: 合法, -1:非法
     * /
     */
    #[TarsReturnType("int")]
    public function checkConfigByInfo(
        #[TarsParameter(type: "ConfigInfo")] ConfigInfo $configInfo,
        #[TarsParameter(type: "string")] ?string &$result
    ): int;

    /**
     * 获取服务的所有配置文件列表，
     * @tars-param configInfo 支持拉取应用配置列表，服务配置列表，机器配置列表
     * @tars-param [out] vf  获取到的文件名称列表
     * @tars-return int 0: 成功, -1:失败
     * /
     */
    #[TarsReturnType("int")]
    public function ListAllConfigByInfo(
        #[TarsParameter(type: "GetConfigListInfo")] GetConfigListInfo $configInfo,
        #[TarsParameter(type: "vector<string>")] ?array &$vf
    ): int;

}
