<?php

declare(strict_types=1);

/**
 * NOTE: This class is auto generated by Tars Generator (https://github.com/wenbinye/tars-generator).
 *
 * Do not edit the class manually.
 * Tars Generator version: 0.6
 */

namespace kuiper\tars\integration;

use kuiper\tars\attribute\TarsProperty;

final class GetConfigListInfo
{
    /**
     * @var string
     */
    #[TarsProperty(type: "string", order: 0)]
    public readonly string $appname;

    /**
     * @var string|null
     */
    #[TarsProperty(type: "string", order: 1)]
    public readonly ?string $servername;

    /**
     * @var bool|null
     */
    #[TarsProperty(type: "bool", order: 2)]
    public readonly ?bool $bAppOnly;

    /**
     * @var string|null
     */
    #[TarsProperty(type: "string", order: 3)]
    public readonly ?string $host;

    /**
     * @var string|null
     */
    #[TarsProperty(type: "string", order: 4)]
    public readonly ?string $setdivision;

    /**
     * @var string|null
     */
    #[TarsProperty(type: "string", order: 5)]
    public readonly ?string $containername;

    public function __construct(
        string $appname,
        ?string $servername = null,
        ?bool $bAppOnly = null,
        ?string $host = null,
        ?string $setdivision = null,
        ?string $containername = null
    ) {
          $this->appname = $appname;
          $this->servername = $servername;
          $this->bAppOnly = $bAppOnly;
          $this->host = $host;
          $this->setdivision = $setdivision;
          $this->containername = $containername;
    }
}
