<?php

declare(strict_types=1);

/*
 * This file is part of the Kuiper package.
 *
 * (c) Ye Wenbin <wenbinye@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

/**
 * NOTE: This class is auto generated by Tars Generator (https://github.com/wenbinye/tars-generator).
 *
 * Do not edit the class manually.
 * Tars Generator version: 1.0
 */

namespace kuiper\tars\integration;

use kuiper\tars\annotation\TarsProperty;

final class LogInfo
{
    /**
     * @TarsProperty(order=0, required=true, type="string")
     *
     * @var string|null
     */
    public $appname;

    /**
     * @TarsProperty(order=1, required=true, type="string")
     *
     * @var string|null
     */
    public $servername;

    /**
     * @TarsProperty(order=2, required=true, type="string")
     *
     * @var string|null
     */
    public $sFilename;

    /**
     * @TarsProperty(order=3, required=true, type="string")
     *
     * @var string|null
     */
    public $sFormat;

    /**
     * @TarsProperty(order=4, required=false, type="string")
     *
     * @var string|null
     */
    public $setdivision;

    /**
     * @TarsProperty(order=5, required=false, type="bool")
     *
     * @var bool|null
     */
    public $bHasSufix = true;

    /**
     * @TarsProperty(order=6, required=false, type="bool")
     *
     * @var bool|null
     */
    public $bHasAppNamePrefix = true;

    /**
     * @TarsProperty(order=7, required=false, type="bool")
     *
     * @var bool|null
     */
    public $bHasSquareBracket = false;

    /**
     * @TarsProperty(order=8, required=false, type="string")
     *
     * @var string|null
     */
    public $sConcatStr = '_';

    /**
     * @TarsProperty(order=9, required=false, type="string")
     *
     * @var string|null
     */
    public $sSepar = '|';

    /**
     * @TarsProperty(order=10, required=false, type="string")
     *
     * @var string|null
     */
    public $sLogType = '';
}
