<?php

declare(strict_types=1);

/**
 * NOTE: This class is auto generated by Tars Generator (https://github.com/wenbinye/tars-generator).
 *
 * Do not edit the class manually.
 * Tars Generator version: 0.6
 */

namespace kuiper\tars\integration;

use kuiper\tars\attribute\TarsProperty;

final class ProxyInfo
{
    /**
     * @var bool
     */
    #[TarsProperty(type: "bool", order: 0)]
    public readonly bool $bFromClient;

    public function __construct(
        bool $bFromClient
    ) {
          $this->bFromClient = $bFromClient;
    }
}
