<?php

/*
 * This file is part of the Kuiper package.
 *
 * (c) Ye Wenbin <wenbinye@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */


declare(strict_types=1);

/**
 * NOTE: This class is auto generated by Tars Generator (https://github.com/wenbinye/tars-generator).
 *
 * Do not edit the class manually.
 * Tars Generator version: 0.6
 */

namespace kuiper\tars\integration;

use kuiper\tars\attribute\TarsClient;
use kuiper\tars\attribute\TarsParameter;
use kuiper\tars\attribute\TarsReturnType;

#[TarsClient("tars.tarsnode.ServerObj")]
interface ServerFServant
{
    /**
     * 向node定时上报serverInfo
     * @tars-param serverInfo  服务状态
     * @tars-return int
     */
    #[TarsReturnType("int")]
    public function keepAlive(
        #[TarsParameter(type: "ServerInfo")] ServerInfo $serverInfo
    ): int;

    /**
     * 向node上报TARS版本信息
     * @tars-param string  版本信息
     * @tars-return int
     */
    #[TarsReturnType("int")]
    public function reportVersion(
        #[TarsParameter(type: "string")] string $app,
        #[TarsParameter(type: "string")] string $serverName,
        #[TarsParameter(type: "string")] string $version
    ): int;

}
