<?php

/*
 * This file is part of the Kuiper package.
 *
 * (c) Ye Wenbin <wenbinye@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */


declare(strict_types=1);

/**
 * NOTE: This class is auto generated by Tars Generator (https://github.com/wenbinye/tars-generator).
 *
 * Do not edit the class manually.
 * Tars Generator version: 0.6
 */

namespace kuiper\tars\integration;

use kuiper\tars\attribute\TarsProperty;

final class ServerInfo
{
    /**
     * @var string
     */
    #[TarsProperty(type: "string", order: 0)]
    public readonly string $application;

    /**
     * @var string
     */
    #[TarsProperty(type: "string", order: 1)]
    public readonly string $serverName;

    /**
     * @var int
     */
    #[TarsProperty(type: "int", order: 2)]
    public readonly int $pid;

    /**
     * @var string|null
     */
    #[TarsProperty(type: "string", order: 3)]
    public readonly ?string $adapter;

    public function __construct(
        string $application,
        string $serverName,
        int $pid,
        ?string $adapter = null
    ) {
          $this->application = $application;
          $this->serverName = $serverName;
          $this->pid = $pid;
          $this->adapter = $adapter;
    }
}
