<?php

/*
 * This file is part of the Kuiper package.
 *
 * (c) Ye Wenbin <wenbinye@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

declare(strict_types=1);

/**
 * NOTE: This class is auto generated by Tars Generator (https://github.com/wenbinye/tars-generator).
 *
 * Do not edit the class manually.
 * Tars Generator version: 0.6
 */

namespace kuiper\tars\integration;

use kuiper\tars\attribute\TarsProperty;

final class StatPropMsgHead
{
    /**
     * @var string
     */
    #[TarsProperty(type: 'string', order: 0)]
    public readonly string $moduleName;

    /**
     * @var string
     */
    #[TarsProperty(type: 'string', order: 1)]
    public readonly string $ip;

    /**
     * @var string
     */
    #[TarsProperty(type: 'string', order: 2)]
    public readonly string $propertyName;

    /**
     * @var string|null
     */
    #[TarsProperty(type: 'string', order: 3)]
    public readonly ?string $setName;

    /**
     * @var string|null
     */
    #[TarsProperty(type: 'string', order: 4)]
    public readonly ?string $setArea;

    /**
     * @var string|null
     */
    #[TarsProperty(type: 'string', order: 5)]
    public readonly ?string $setID;

    /**
     * @var string|null
     */
    #[TarsProperty(type: 'string', order: 6)]
    public readonly ?string $sContainer;

    /**
     * @var int|null
     */
    #[TarsProperty(type: 'int', order: 7)]
    public readonly ?int $iPropertyVer;

    public function __construct(
        string $moduleName,
        string $ip,
        string $propertyName,
        ?string $setName = null,
        ?string $setArea = null,
        ?string $setID = null,
        ?string $sContainer = null,
        ?int $iPropertyVer = null
    ) {
        $this->moduleName = $moduleName;
        $this->ip = $ip;
        $this->propertyName = $propertyName;
        $this->setName = $setName;
        $this->setArea = $setArea;
        $this->setID = $setID;
        $this->sContainer = $sContainer;
        $this->iPropertyVer = $iPropertyVer;
    }
}
