<?php

declare(strict_types=1);

/**
 * NOTE: This class is auto generated by Tars Generator (https://github.com/wenbinye/tars-generator).
 *
 * Do not edit the class manually.
 * Tars Generator version: 0.6
 */

namespace kuiper\tars\integration;

use kuiper\tars\attribute\TarsClient;
use kuiper\tars\attribute\TarsParameter;
use kuiper\tars\attribute\TarsReturnType;

#[TarsClient("tars.tarsstat.StatObj")]
interface StatFServant
{
    /**
     * 上报模块间调用信息 Mic = module interval call
     * @tars-param statmsg,             上报信息
     * @tars-param bFromServer,         上报源  bFromClient: true 客户端发起的上报 false 服务端发起上报
     * @tars-return int,                返回0表示成功
     */
    #[TarsReturnType("int")]
    public function reportMicMsg(
        #[TarsParameter(type: "map<StatMicMsgHead,StatMicMsgBody>")] $msg,
        #[TarsParameter(type: "bool")] bool $bFromClient
    ): int;

    /**
     * 上报模块间调用采样信息 Mic = module interval call
     * @tars-param msg,               上报信息
     * @tars-return int,                返回0表示成功
     */
    #[TarsReturnType("int")]
    public function reportSampleMsg(
        #[TarsParameter(type: "vector<StatSampleMsg>")] array $msg
    ): int;

}
