<?php

/*
 * This file is part of the Kuiper package.
 *
 * (c) Ye Wenbin <wenbinye@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */


declare(strict_types=1);

/**
 * NOTE: This class is auto generated by Tars Generator (https://github.com/wenbinye/tars-generator).
 *
 * Do not edit the class manually.
 * Tars Generator version: 0.6
 */

namespace kuiper\tars\integration;

use kuiper\tars\attribute\TarsProperty;

final class StatMicMsgBody
{
    /**
     * @var int
     */
    #[TarsProperty(type: "int", order: 0)]
    public readonly int $count;

    /**
     * @var int
     */
    #[TarsProperty(type: "int", order: 1)]
    public readonly int $timeoutCount;

    /**
     * @var int
     */
    #[TarsProperty(type: "int", order: 2)]
    public readonly int $execCount;

    /**
     * @var int[]
     */
    #[TarsProperty(type: "map<int,int>", order: 3)]
    public readonly array $intervalCount;

    /**
     * @var int
     */
    #[TarsProperty(type: "long", order: 4)]
    public readonly int $totalRspTime;

    /**
     * @var int
     */
    #[TarsProperty(type: "int", order: 5)]
    public readonly int $maxRspTime;

    /**
     * @var int
     */
    #[TarsProperty(type: "int", order: 6)]
    public readonly int $minRspTime;

    public function __construct(
        int $count,
        int $timeoutCount,
        int $execCount,
        array $intervalCount,
        int $totalRspTime,
        int $maxRspTime,
        int $minRspTime
    ) {
          $this->count = $count;
          $this->timeoutCount = $timeoutCount;
          $this->execCount = $execCount;
          $this->intervalCount = $intervalCount;
          $this->totalRspTime = $totalRspTime;
          $this->maxRspTime = $maxRspTime;
          $this->minRspTime = $minRspTime;
    }
}
