<?php

declare(strict_types=1);

/**
 * NOTE: This class is auto generated by Tars Generator (https://github.com/wenbinye/tars-generator).
 *
 * Do not edit the class manually.
 * Tars Generator version: 0.6
 */

namespace kuiper\tars\integration;

use kuiper\tars\attribute\TarsProperty;

final class StatPropMsgBody
{
    /**
     * @var StatPropInfo[]
     */
    #[TarsProperty(type: "vector<StatPropInfo>", order: 0)]
    public readonly array $vInfo;

    public function __construct(
        array $vInfo
    ) {
          $this->vInfo = $vInfo;
    }
}
