<?php

/*
 * This file is part of the Kuiper package.
 *
 * (c) Ye Wenbin <wenbinye@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

declare(strict_types=1);

/**
 * NOTE: This class is auto generated by Tars Generator (https://github.com/wenbinye/tars-generator).
 *
 * Do not edit the class manually.
 * Tars Generator version: 0.6
 */

namespace kuiper\tars\server\servant;

use kuiper\tars\attribute\TarsParameter;
use kuiper\tars\attribute\TarsReturnType;
use kuiper\tars\attribute\TarsServant;

#[TarsServant('AdminObj')]
interface AdminServant
{
    /**
     * For healthy check.
     */
    #[TarsReturnType('string')]
    public function ping(): string;

    /**
     * Get server stat.
     */
    #[TarsReturnType('Stat')]
    public function stats(): Stat;

    /**
     * receive notification.
     */
    #[TarsReturnType('void')]
    public function notify(
        #[TarsParameter(type: 'Notification')] Notification $notification
    ): void;

    /**
     * Gets servant files.
     */
    #[TarsReturnType('vector<TarsFile>')]
    public function getTarsFiles(): array;

    /**
     * Gets servant file with content.
     */
    #[TarsReturnType('vector<TarsFile>')]
    public function getTarsFileContents(): array;
}
