<?php

declare(strict_types=1);

/**
 * NOTE: This class is auto generated by Tars Generator (https://github.com/wenbinye/tars-generator).
 *
 * Do not edit the class manually.
 * Tars Generator version: 1.0
 */

namespace kuiper\tars\server\servant;

use kuiper\tars\annotation\TarsProperty;

final class Notification
{
    /**
     * @TarsProperty(order=0, required=true, type="string")
     *
     * @var string|null
     */
    public $createTime;

    /**
     * @TarsProperty(order=1, required=true, type="string")
     *
     * @var string|null
     */
    public $eventId;

    /**
     * @TarsProperty(order=2, required=true, type="string")
     *
     * @var string|null
     */
    public $topic;

    /**
     * @TarsProperty(order=3, required=true, type="string")
     *
     * @var string|null
     */
    public $eventName;

    /**
     * @TarsProperty(order=4, required=true, type="string")
     *
     * @var string|null
     */
    public $payload;
}
