<?php

declare(strict_types=1);

/**
 * NOTE: This class is auto generated by Tars Generator (https://github.com/wenbinye/tars-generator).
 *
 * Do not edit the class manually.
 * Tars Generator version: 0.6
 */

namespace kuiper\tars\server\servant;

use kuiper\tars\attribute\TarsProperty;

final class Notification
{
    /**
     * @var string
     */
    #[TarsProperty(type: "string", order: 0)]
    public readonly string $createTime;

    /**
     * @var string
     */
    #[TarsProperty(type: "string", order: 1)]
    public readonly string $eventId;

    /**
     * @var string
     */
    #[TarsProperty(type: "string", order: 2)]
    public readonly string $topic;

    /**
     * @var string
     */
    #[TarsProperty(type: "string", order: 3)]
    public readonly string $eventName;

    /**
     * @var string
     */
    #[TarsProperty(type: "string", order: 4)]
    public readonly string $payload;

    public function __construct(
        string $createTime,
        string $eventId,
        string $topic,
        string $eventName,
        string $payload
    ) {
          $this->createTime = $createTime;
          $this->eventId = $eventId;
          $this->topic = $topic;
          $this->eventName = $eventName;
          $this->payload = $payload;
    }
}
