<?php

declare(strict_types=1);

/*
 * This file is part of the Kuiper package.
 *
 * (c) Ye Wenbin <wenbinye@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

/**
 * NOTE: This class is auto generated by Tars Generator (https://github.com/wenbinye/tars-generator).
 *
 * Do not edit the class manually.
 * Tars Generator version: 1.0
 */

namespace kuiper\tars\server\servant;

use kuiper\tars\annotation\TarsProperty;

final class Stat
{
    /**
     * @TarsProperty(order=0, required=true, type="string")
     *
     * @var string|null
     */
    public $startTime;

    /**
     * @TarsProperty(order=1, required=true, type="int")
     *
     * @var int|null
     */
    public $connections;

    /**
     * @TarsProperty(order=2, required=true, type="int")
     *
     * @var int|null
     */
    public $acceptCount;

    /**
     * @TarsProperty(order=3, required=true, type="int")
     *
     * @var int|null
     */
    public $closeCount;

    /**
     * @TarsProperty(order=4, required=true, type="int")
     *
     * @var int|null
     */
    public $requestCount;

    /**
     * @TarsProperty(order=5, required=true, type="int")
     *
     * @var int|null
     */
    public $dispatchCount;

    /**
     * @TarsProperty(order=6, required=true, type="int")
     *
     * @var int|null
     */
    public $pendingTasks;
}
