#!/usr/bin/env php
<?php

ini_set('memory_limit', -1);
ini_set('display_errors', 'on');
ini_set('default_socket_timeout', -1);

$loader = require __DIR__ . '/vendor/autoload.php';

$app = new kuiper\boot\Application();
$app->setLoader($loader)
    ->useAnnotations()
    ->loadConfig(__DIR__.'/config')
    ->bootstrap()
    ->get(Symfony\Component\Console\Application::class)
    ->run();
